function k_PML = k_sym_discontinua3_PML22(XYelement,beta_0_x,beta_0_y,L_PML_x,...
    L_PML_y,xi,yj,rho,E,nu) 
% k_elemental_PML11                                % matriz de rigidez de 
% elemento PML
% 6.21.2021                                        % Adriano Trono

% discontinua3: tres incógnitas de tensión constante en el elemento...
% Lambda: primera constante de Lamé...
% códigonumérico ## de k_elemental_PML## --->  ## = m_x m_y 
% 22 significa que m_x = 2, m_y = 2;
% lambda_x = alpha_x + beta_x/(j omega)
% beta_x   = ((x - xlim)/L_PML_x)^m_x
% Debido a que la matriz de rigidez ddepende exclusivamente de los beta_x y 
% beta_y el código 11 significa que beta varía linealmente tanto en x como 
% en y

% Orden de los grados de libertad...
% X = [ui_x; ui_y; uj_x; uj_y; uk_x; uk_y; ul_x; ul_y; Si_11; Si_22; Si_12;
% Sj_11; Sj_22; Sj_12; Sk_11; Sk_22; Sk_12; Sl_11; Sl_22; Sl_12];...
% xi    : abscisa donde arranca el elemento finito (nudo i o j indistinto)
% yj    : ordenada donde arranca el elemento finito (nudo j o k indistinto)
% L_PML_x: longitud x de la PML, puede ser positiva o negativa porque
% L_PML_x = x_exterior - x_interior, con x_interior en contacto con el domi_
% nio regular...

%           ^ y_PML      ^ ye
%           |            |
%           |            |
%           |                  a
%           |          i o --------- o l
%           |---- xi ----|           |
%           |         b  |           |
%           |            |           |
%           |          j o --------- o k    ------> xe
%           |            | 
%DOMINIO    |            yj                  DOMINIO 
%REGULAR    |            |                     PML
%          -|----------------------------------------------> x_PML
%           |
%           |       
a = abs(XYelement(7) - XYelement(1));
b = abs(XYelement(2) - XYelement(4));

k_PML = [    (a*b*beta_0_x*beta_0_y*rho*(a^2 + 5*a*xi + 10*xi^2)*(6*b^2 + 15*b*yj + 10*yj^2))/(900*L_PML_x^2*L_PML_y^2),                                                                                                              0,    (a*b*beta_0_x*beta_0_y*rho*(a^2 + 5*a*xi + 10*xi^2)*(3*b^2 + 10*b*yj + 10*yj^2))/(1800*L_PML_x^2*L_PML_y^2),                                                                                                              0, (a*b*beta_0_x*beta_0_y*rho*(3*a^2 + 10*a*xi + 10*xi^2)*(3*b^2 + 10*b*yj + 10*yj^2))/(3600*L_PML_x^2*L_PML_y^2),                                                                                                              0, (a*b*beta_0_x*beta_0_y*rho*(3*a^2 + 10*a*xi + 10*xi^2)*(6*b^2 + 15*b*yj + 10*yj^2))/(1800*L_PML_x^2*L_PML_y^2),                                                                                                              0,                                                        -(b*beta_0_y*(3*b^2 + 8*b*yj + 6*yj^2))/(12*L_PML_y^2),                                                                                                             0,                                                           (a*beta_0_x*(a^2 + 4*a*xi + 6*xi^2))/(12*L_PML_x^2);
                                                                                                                      0,     (a*b*beta_0_x*beta_0_y*rho*(a^2 + 5*a*xi + 10*xi^2)*(6*b^2 + 15*b*yj + 10*yj^2))/(900*L_PML_x^2*L_PML_y^2),                                                                                                              0,    (a*b*beta_0_x*beta_0_y*rho*(a^2 + 5*a*xi + 10*xi^2)*(3*b^2 + 10*b*yj + 10*yj^2))/(1800*L_PML_x^2*L_PML_y^2),                                                                                                              0, (a*b*beta_0_x*beta_0_y*rho*(3*a^2 + 10*a*xi + 10*xi^2)*(3*b^2 + 10*b*yj + 10*yj^2))/(3600*L_PML_x^2*L_PML_y^2),                                                                                                              0, (a*b*beta_0_x*beta_0_y*rho*(3*a^2 + 10*a*xi + 10*xi^2)*(6*b^2 + 15*b*yj + 10*yj^2))/(1800*L_PML_x^2*L_PML_y^2),                                                                                                             0,                                                           (a*beta_0_x*(a^2 + 4*a*xi + 6*xi^2))/(12*L_PML_x^2),                                                        -(b*beta_0_y*(3*b^2 + 8*b*yj + 6*yj^2))/(12*L_PML_y^2);
            (a*b*beta_0_x*beta_0_y*rho*(a^2 + 5*a*xi + 10*xi^2)*(3*b^2 + 10*b*yj + 10*yj^2))/(1800*L_PML_x^2*L_PML_y^2),                                                                                                              0,        (a*b*beta_0_x*beta_0_y*rho*(a^2 + 5*a*xi + 10*xi^2)*(b^2 + 5*b*yj + 10*yj^2))/(900*L_PML_x^2*L_PML_y^2),                                                                                                              0,    (a*b*beta_0_x*beta_0_y*rho*(b^2 + 5*b*yj + 10*yj^2)*(3*a^2 + 10*a*xi + 10*xi^2))/(1800*L_PML_x^2*L_PML_y^2),                                                                                                              0, (a*b*beta_0_x*beta_0_y*rho*(3*a^2 + 10*a*xi + 10*xi^2)*(3*b^2 + 10*b*yj + 10*yj^2))/(3600*L_PML_x^2*L_PML_y^2),                                                                                                              0,                                                          -(b*beta_0_y*(b^2 + 4*b*yj + 6*yj^2))/(12*L_PML_y^2),                                                                                                             0,                                                          -(a*beta_0_x*(a^2 + 4*a*xi + 6*xi^2))/(12*L_PML_x^2);
                                                                                                                      0,    (a*b*beta_0_x*beta_0_y*rho*(a^2 + 5*a*xi + 10*xi^2)*(3*b^2 + 10*b*yj + 10*yj^2))/(1800*L_PML_x^2*L_PML_y^2),                                                                                                              0,        (a*b*beta_0_x*beta_0_y*rho*(a^2 + 5*a*xi + 10*xi^2)*(b^2 + 5*b*yj + 10*yj^2))/(900*L_PML_x^2*L_PML_y^2),                                                                                                              0,    (a*b*beta_0_x*beta_0_y*rho*(b^2 + 5*b*yj + 10*yj^2)*(3*a^2 + 10*a*xi + 10*xi^2))/(1800*L_PML_x^2*L_PML_y^2),                                                                                                              0, (a*b*beta_0_x*beta_0_y*rho*(3*a^2 + 10*a*xi + 10*xi^2)*(3*b^2 + 10*b*yj + 10*yj^2))/(3600*L_PML_x^2*L_PML_y^2),                                                                                                             0,                                                          -(a*beta_0_x*(a^2 + 4*a*xi + 6*xi^2))/(12*L_PML_x^2),                                                          -(b*beta_0_y*(b^2 + 4*b*yj + 6*yj^2))/(12*L_PML_y^2);
         (a*b*beta_0_x*beta_0_y*rho*(3*a^2 + 10*a*xi + 10*xi^2)*(3*b^2 + 10*b*yj + 10*yj^2))/(3600*L_PML_x^2*L_PML_y^2),                                                                                                              0,    (a*b*beta_0_x*beta_0_y*rho*(b^2 + 5*b*yj + 10*yj^2)*(3*a^2 + 10*a*xi + 10*xi^2))/(1800*L_PML_x^2*L_PML_y^2),                                                                                                              0,     (a*b*beta_0_x*beta_0_y*rho*(b^2 + 5*b*yj + 10*yj^2)*(6*a^2 + 15*a*xi + 10*xi^2))/(900*L_PML_x^2*L_PML_y^2),                                                                                                              0, (a*b*beta_0_x*beta_0_y*rho*(6*a^2 + 15*a*xi + 10*xi^2)*(3*b^2 + 10*b*yj + 10*yj^2))/(1800*L_PML_x^2*L_PML_y^2),                                                                                                              0,                                                           (b*beta_0_y*(b^2 + 4*b*yj + 6*yj^2))/(12*L_PML_y^2),                                                                                                             0,                                                        -(a*beta_0_x*(3*a^2 + 8*a*xi + 6*xi^2))/(12*L_PML_x^2);
                                                                                                                      0, (a*b*beta_0_x*beta_0_y*rho*(3*a^2 + 10*a*xi + 10*xi^2)*(3*b^2 + 10*b*yj + 10*yj^2))/(3600*L_PML_x^2*L_PML_y^2),                                                                                                              0,    (a*b*beta_0_x*beta_0_y*rho*(b^2 + 5*b*yj + 10*yj^2)*(3*a^2 + 10*a*xi + 10*xi^2))/(1800*L_PML_x^2*L_PML_y^2),                                                                                                              0,     (a*b*beta_0_x*beta_0_y*rho*(b^2 + 5*b*yj + 10*yj^2)*(6*a^2 + 15*a*xi + 10*xi^2))/(900*L_PML_x^2*L_PML_y^2),                                                                                                              0, (a*b*beta_0_x*beta_0_y*rho*(6*a^2 + 15*a*xi + 10*xi^2)*(3*b^2 + 10*b*yj + 10*yj^2))/(1800*L_PML_x^2*L_PML_y^2),                                                                                                             0,                                                        -(a*beta_0_x*(3*a^2 + 8*a*xi + 6*xi^2))/(12*L_PML_x^2),                                                           (b*beta_0_y*(b^2 + 4*b*yj + 6*yj^2))/(12*L_PML_y^2);
         (a*b*beta_0_x*beta_0_y*rho*(3*a^2 + 10*a*xi + 10*xi^2)*(6*b^2 + 15*b*yj + 10*yj^2))/(1800*L_PML_x^2*L_PML_y^2),                                                                                                              0, (a*b*beta_0_x*beta_0_y*rho*(3*a^2 + 10*a*xi + 10*xi^2)*(3*b^2 + 10*b*yj + 10*yj^2))/(3600*L_PML_x^2*L_PML_y^2),                                                                                                              0, (a*b*beta_0_x*beta_0_y*rho*(6*a^2 + 15*a*xi + 10*xi^2)*(3*b^2 + 10*b*yj + 10*yj^2))/(1800*L_PML_x^2*L_PML_y^2),                                                                                                              0,  (a*b*beta_0_x*beta_0_y*rho*(6*a^2 + 15*a*xi + 10*xi^2)*(6*b^2 + 15*b*yj + 10*yj^2))/(900*L_PML_x^2*L_PML_y^2),                                                                                                              0,                                                         (b*beta_0_y*(3*b^2 + 8*b*yj + 6*yj^2))/(12*L_PML_y^2),                                                                                                             0,                                                         (a*beta_0_x*(3*a^2 + 8*a*xi + 6*xi^2))/(12*L_PML_x^2);
                                                                                                                      0, (a*b*beta_0_x*beta_0_y*rho*(3*a^2 + 10*a*xi + 10*xi^2)*(6*b^2 + 15*b*yj + 10*yj^2))/(1800*L_PML_x^2*L_PML_y^2),                                                                                                              0, (a*b*beta_0_x*beta_0_y*rho*(3*a^2 + 10*a*xi + 10*xi^2)*(3*b^2 + 10*b*yj + 10*yj^2))/(3600*L_PML_x^2*L_PML_y^2),                                                                                                              0, (a*b*beta_0_x*beta_0_y*rho*(6*a^2 + 15*a*xi + 10*xi^2)*(3*b^2 + 10*b*yj + 10*yj^2))/(1800*L_PML_x^2*L_PML_y^2),                                                                                                              0,  (a*b*beta_0_x*beta_0_y*rho*(6*a^2 + 15*a*xi + 10*xi^2)*(6*b^2 + 15*b*yj + 10*yj^2))/(900*L_PML_x^2*L_PML_y^2),                                                                                                             0,                                                         (a*beta_0_x*(3*a^2 + 8*a*xi + 6*xi^2))/(12*L_PML_x^2),                                                         (b*beta_0_y*(3*b^2 + 8*b*yj + 6*yj^2))/(12*L_PML_y^2);
                                                                 -(b*beta_0_y*(3*b^2 + 8*b*yj + 6*yj^2))/(12*L_PML_y^2),                                                                                                              0,                                                           -(b*beta_0_y*(b^2 + 4*b*yj + 6*yj^2))/(12*L_PML_y^2),                                                                                                              0,                                                            (b*beta_0_y*(b^2 + 4*b*yj + 6*yj^2))/(12*L_PML_y^2),                                                                                                              0,                                                          (b*beta_0_y*(3*b^2 + 8*b*yj + 6*yj^2))/(12*L_PML_y^2),                                                                                                              0,  (a*b*beta_0_x*beta_0_y*(nu^2 - 1)*(a^2 + 3*a*xi + 3*xi^2)*(b^2 + 3*b*yj + 3*yj^2))/(9*E*L_PML_x^2*L_PML_y^2), (a*b*beta_0_x*beta_0_y*nu*(nu + 1)*(a^2 + 3*a*xi + 3*xi^2)*(b^2 + 3*b*yj + 3*yj^2))/(9*E*L_PML_x^2*L_PML_y^2),                                                                                                             0;
                                                                                                                      0,                                                            (a*beta_0_x*(a^2 + 4*a*xi + 6*xi^2))/(12*L_PML_x^2),                                                                                                              0,                                                           -(a*beta_0_x*(a^2 + 4*a*xi + 6*xi^2))/(12*L_PML_x^2),                                                                                                              0,                                                         -(a*beta_0_x*(3*a^2 + 8*a*xi + 6*xi^2))/(12*L_PML_x^2),                                                                                                              0,                                                          (a*beta_0_x*(3*a^2 + 8*a*xi + 6*xi^2))/(12*L_PML_x^2), (a*b*beta_0_x*beta_0_y*nu*(nu + 1)*(a^2 + 3*a*xi + 3*xi^2)*(b^2 + 3*b*yj + 3*yj^2))/(9*E*L_PML_x^2*L_PML_y^2),  (a*b*beta_0_x*beta_0_y*(nu^2 - 1)*(a^2 + 3*a*xi + 3*xi^2)*(b^2 + 3*b*yj + 3*yj^2))/(9*E*L_PML_x^2*L_PML_y^2),                                                                                                             0;
                                                                    (a*beta_0_x*(a^2 + 4*a*xi + 6*xi^2))/(12*L_PML_x^2),                                                         -(b*beta_0_y*(3*b^2 + 8*b*yj + 6*yj^2))/(12*L_PML_y^2),                                                           -(a*beta_0_x*(a^2 + 4*a*xi + 6*xi^2))/(12*L_PML_x^2),                                                           -(b*beta_0_y*(b^2 + 4*b*yj + 6*yj^2))/(12*L_PML_y^2),                                                         -(a*beta_0_x*(3*a^2 + 8*a*xi + 6*xi^2))/(12*L_PML_x^2),                                                            (b*beta_0_y*(b^2 + 4*b*yj + 6*yj^2))/(12*L_PML_y^2),                                                          (a*beta_0_x*(3*a^2 + 8*a*xi + 6*xi^2))/(12*L_PML_x^2),                                                          (b*beta_0_y*(3*b^2 + 8*b*yj + 6*yj^2))/(12*L_PML_y^2),                                                                                                             0,                                                                                                             0, -(2*a*b*beta_0_x*beta_0_y*(nu + 1)*(a^2 + 3*a*xi + 3*xi^2)*(b^2 + 3*b*yj + 3*yj^2))/(9*E*L_PML_x^2*L_PML_y^2)];