function m_PML = m_sym_discontinua3_PML22(XYelement,alpha_0_x,alpha_0_y,L_PML_x,...
    L_PML_y,xi,yj,rho,E,nu) 
% m_elemental_PML11                        % matriz de amortiguamiento de 
% elemento PML
% 6.21.2021                                   % Adriano Trono

% discontinua5: se refiere a que se trabaja con 5 incógnitas de tensión por
% elemento (PIAN SUMIHARA element)
% E,nu: Young y poisson
% códigonumérico ## de k_elemental_PML## --->  ## = n_x n_y 
% 1111 significa que n_x = m_x = 1, n_y = m_y = 1;
% lambda_x = alpha_x + beta_x/(j omega)
% alpha_x   = 1 + alpha_0_x ((x - xlim)/L_PML_x)^m_x
% Debido a que la matriz de masa ddepende exclusivamente de los alpha_x y 
% alpha_y el código 11 significa que alpha varía linealmente y
% que beta también

% Orden de los grados de libertad...
% X = [ui_x; ui_y; uj_x; uj_y; uk_x; uk_y; ul_x; ul_y; Si_11; Si_22; Si_12;
% Sj_11; Sj_22; Sj_12; Sk_11; Sk_22; Sk_12; Sl_11; Sl_22; Sl_12];...
% xi    : abscisa donde arranca el elemento finito (nudo i o j indistinto)
% yj    : ordenada donde arranca el elemento finito (nudo j o k indistinto)
% L_PML_x: longitud x de la PML, puede ser positiva o negativa porque
% L_PML_x = x_exterior - x_interior, con x_interior en contacto con el domi_
% nio regular...

%           ^ y          ^ ye
%           |            |
%           |            |
%           |                  a
%           |          i o --------- o l
%           |---- xi ----|           |
%           |         b  |           |
%           |            |           |
%           |          j o --------- o k    ------> xe
%           |            | 
%           |            yj
%           |            |   
%          -|----------------------------------------------> x
a = abs(XYelement(7) - XYelement(1));
b = abs(XYelement(2) - XYelement(4));

m_PML = [    (a*b*rho*(10*L_PML_x^2 + alpha_0_x*a^2 + 5*alpha_0_x*a*xi + 10*alpha_0_x*xi^2)*(10*L_PML_y^2 + 6*alpha_0_y*b^2 + 15*alpha_0_y*b*yj + 10*alpha_0_y*yj^2))/(900*L_PML_x^2*L_PML_y^2),                                                                                                                                                                                      0,    (a*b*rho*(10*L_PML_x^2 + alpha_0_x*a^2 + 5*alpha_0_x*a*xi + 10*alpha_0_x*xi^2)*(10*L_PML_y^2 + 3*alpha_0_y*b^2 + 10*alpha_0_y*b*yj + 10*alpha_0_y*yj^2))/(1800*L_PML_x^2*L_PML_y^2),                                                                                                                                                                                      0, (a*b*rho*(10*L_PML_x^2 + 3*alpha_0_x*a^2 + 10*alpha_0_x*a*xi + 10*alpha_0_x*xi^2)*(10*L_PML_y^2 + 3*alpha_0_y*b^2 + 10*alpha_0_y*b*yj + 10*alpha_0_y*yj^2))/(3600*L_PML_x^2*L_PML_y^2),                                                                                                                                                                                      0, (a*b*rho*(10*L_PML_x^2 + 3*alpha_0_x*a^2 + 10*alpha_0_x*a*xi + 10*alpha_0_x*xi^2)*(10*L_PML_y^2 + 6*alpha_0_y*b^2 + 15*alpha_0_y*b*yj + 10*alpha_0_y*yj^2))/(1800*L_PML_x^2*L_PML_y^2),                                                                                                                                                                                      0,                                                                                                                                                                                   0,                                                                                                                                                                                   0,                                                                                                                                                                                   0;
                                                                                                                                                                                              0,     (a*b*rho*(10*L_PML_x^2 + alpha_0_x*a^2 + 5*alpha_0_x*a*xi + 10*alpha_0_x*xi^2)*(10*L_PML_y^2 + 6*alpha_0_y*b^2 + 15*alpha_0_y*b*yj + 10*alpha_0_y*yj^2))/(900*L_PML_x^2*L_PML_y^2),                                                                                                                                                                                      0,    (a*b*rho*(10*L_PML_x^2 + alpha_0_x*a^2 + 5*alpha_0_x*a*xi + 10*alpha_0_x*xi^2)*(10*L_PML_y^2 + 3*alpha_0_y*b^2 + 10*alpha_0_y*b*yj + 10*alpha_0_y*yj^2))/(1800*L_PML_x^2*L_PML_y^2),                                                                                                                                                                                      0, (a*b*rho*(10*L_PML_x^2 + 3*alpha_0_x*a^2 + 10*alpha_0_x*a*xi + 10*alpha_0_x*xi^2)*(10*L_PML_y^2 + 3*alpha_0_y*b^2 + 10*alpha_0_y*b*yj + 10*alpha_0_y*yj^2))/(3600*L_PML_x^2*L_PML_y^2),                                                                                                                                                                                      0, (a*b*rho*(10*L_PML_x^2 + 3*alpha_0_x*a^2 + 10*alpha_0_x*a*xi + 10*alpha_0_x*xi^2)*(10*L_PML_y^2 + 6*alpha_0_y*b^2 + 15*alpha_0_y*b*yj + 10*alpha_0_y*yj^2))/(1800*L_PML_x^2*L_PML_y^2),                                                                                                                                                                                   0,                                                                                                                                                                                   0,                                                                                                                                                                                   0;
            (a*b*rho*(10*L_PML_x^2 + alpha_0_x*a^2 + 5*alpha_0_x*a*xi + 10*alpha_0_x*xi^2)*(10*L_PML_y^2 + 3*alpha_0_y*b^2 + 10*alpha_0_y*b*yj + 10*alpha_0_y*yj^2))/(1800*L_PML_x^2*L_PML_y^2),                                                                                                                                                                                      0,        (a*b*rho*(10*L_PML_x^2 + alpha_0_x*a^2 + 5*alpha_0_x*a*xi + 10*alpha_0_x*xi^2)*(10*L_PML_y^2 + alpha_0_y*b^2 + 5*alpha_0_y*b*yj + 10*alpha_0_y*yj^2))/(900*L_PML_x^2*L_PML_y^2),                                                                                                                                                                                      0,    (a*b*rho*(10*L_PML_x^2 + 3*alpha_0_x*a^2 + 10*alpha_0_x*a*xi + 10*alpha_0_x*xi^2)*(10*L_PML_y^2 + alpha_0_y*b^2 + 5*alpha_0_y*b*yj + 10*alpha_0_y*yj^2))/(1800*L_PML_x^2*L_PML_y^2),                                                                                                                                                                                      0, (a*b*rho*(10*L_PML_x^2 + 3*alpha_0_x*a^2 + 10*alpha_0_x*a*xi + 10*alpha_0_x*xi^2)*(10*L_PML_y^2 + 3*alpha_0_y*b^2 + 10*alpha_0_y*b*yj + 10*alpha_0_y*yj^2))/(3600*L_PML_x^2*L_PML_y^2),                                                                                                                                                                                      0,                                                                                                                                                                                   0,                                                                                                                                                                                   0,                                                                                                                                                                                   0;
                                                                                                                                                                                              0,    (a*b*rho*(10*L_PML_x^2 + alpha_0_x*a^2 + 5*alpha_0_x*a*xi + 10*alpha_0_x*xi^2)*(10*L_PML_y^2 + 3*alpha_0_y*b^2 + 10*alpha_0_y*b*yj + 10*alpha_0_y*yj^2))/(1800*L_PML_x^2*L_PML_y^2),                                                                                                                                                                                      0,        (a*b*rho*(10*L_PML_x^2 + alpha_0_x*a^2 + 5*alpha_0_x*a*xi + 10*alpha_0_x*xi^2)*(10*L_PML_y^2 + alpha_0_y*b^2 + 5*alpha_0_y*b*yj + 10*alpha_0_y*yj^2))/(900*L_PML_x^2*L_PML_y^2),                                                                                                                                                                                      0,    (a*b*rho*(10*L_PML_x^2 + 3*alpha_0_x*a^2 + 10*alpha_0_x*a*xi + 10*alpha_0_x*xi^2)*(10*L_PML_y^2 + alpha_0_y*b^2 + 5*alpha_0_y*b*yj + 10*alpha_0_y*yj^2))/(1800*L_PML_x^2*L_PML_y^2),                                                                                                                                                                                      0, (a*b*rho*(10*L_PML_x^2 + 3*alpha_0_x*a^2 + 10*alpha_0_x*a*xi + 10*alpha_0_x*xi^2)*(10*L_PML_y^2 + 3*alpha_0_y*b^2 + 10*alpha_0_y*b*yj + 10*alpha_0_y*yj^2))/(3600*L_PML_x^2*L_PML_y^2),                                                                                                                                                                                   0,                                                                                                                                                                                   0,                                                                                                                                                                                   0;
         (a*b*rho*(10*L_PML_x^2 + 3*alpha_0_x*a^2 + 10*alpha_0_x*a*xi + 10*alpha_0_x*xi^2)*(10*L_PML_y^2 + 3*alpha_0_y*b^2 + 10*alpha_0_y*b*yj + 10*alpha_0_y*yj^2))/(3600*L_PML_x^2*L_PML_y^2),                                                                                                                                                                                      0,    (a*b*rho*(10*L_PML_x^2 + 3*alpha_0_x*a^2 + 10*alpha_0_x*a*xi + 10*alpha_0_x*xi^2)*(10*L_PML_y^2 + alpha_0_y*b^2 + 5*alpha_0_y*b*yj + 10*alpha_0_y*yj^2))/(1800*L_PML_x^2*L_PML_y^2),                                                                                                                                                                                      0,     (a*b*rho*(10*L_PML_x^2 + 6*alpha_0_x*a^2 + 15*alpha_0_x*a*xi + 10*alpha_0_x*xi^2)*(10*L_PML_y^2 + alpha_0_y*b^2 + 5*alpha_0_y*b*yj + 10*alpha_0_y*yj^2))/(900*L_PML_x^2*L_PML_y^2),                                                                                                                                                                                      0, (a*b*rho*(10*L_PML_x^2 + 6*alpha_0_x*a^2 + 15*alpha_0_x*a*xi + 10*alpha_0_x*xi^2)*(10*L_PML_y^2 + 3*alpha_0_y*b^2 + 10*alpha_0_y*b*yj + 10*alpha_0_y*yj^2))/(1800*L_PML_x^2*L_PML_y^2),                                                                                                                                                                                      0,                                                                                                                                                                                   0,                                                                                                                                                                                   0,                                                                                                                                                                                   0;
                                                                                                                                                                                              0, (a*b*rho*(10*L_PML_x^2 + 3*alpha_0_x*a^2 + 10*alpha_0_x*a*xi + 10*alpha_0_x*xi^2)*(10*L_PML_y^2 + 3*alpha_0_y*b^2 + 10*alpha_0_y*b*yj + 10*alpha_0_y*yj^2))/(3600*L_PML_x^2*L_PML_y^2),                                                                                                                                                                                      0,    (a*b*rho*(10*L_PML_x^2 + 3*alpha_0_x*a^2 + 10*alpha_0_x*a*xi + 10*alpha_0_x*xi^2)*(10*L_PML_y^2 + alpha_0_y*b^2 + 5*alpha_0_y*b*yj + 10*alpha_0_y*yj^2))/(1800*L_PML_x^2*L_PML_y^2),                                                                                                                                                                                      0,     (a*b*rho*(10*L_PML_x^2 + 6*alpha_0_x*a^2 + 15*alpha_0_x*a*xi + 10*alpha_0_x*xi^2)*(10*L_PML_y^2 + alpha_0_y*b^2 + 5*alpha_0_y*b*yj + 10*alpha_0_y*yj^2))/(900*L_PML_x^2*L_PML_y^2),                                                                                                                                                                                      0, (a*b*rho*(10*L_PML_x^2 + 6*alpha_0_x*a^2 + 15*alpha_0_x*a*xi + 10*alpha_0_x*xi^2)*(10*L_PML_y^2 + 3*alpha_0_y*b^2 + 10*alpha_0_y*b*yj + 10*alpha_0_y*yj^2))/(1800*L_PML_x^2*L_PML_y^2),                                                                                                                                                                                   0,                                                                                                                                                                                   0,                                                                                                                                                                                   0;
         (a*b*rho*(10*L_PML_x^2 + 3*alpha_0_x*a^2 + 10*alpha_0_x*a*xi + 10*alpha_0_x*xi^2)*(10*L_PML_y^2 + 6*alpha_0_y*b^2 + 15*alpha_0_y*b*yj + 10*alpha_0_y*yj^2))/(1800*L_PML_x^2*L_PML_y^2),                                                                                                                                                                                      0, (a*b*rho*(10*L_PML_x^2 + 3*alpha_0_x*a^2 + 10*alpha_0_x*a*xi + 10*alpha_0_x*xi^2)*(10*L_PML_y^2 + 3*alpha_0_y*b^2 + 10*alpha_0_y*b*yj + 10*alpha_0_y*yj^2))/(3600*L_PML_x^2*L_PML_y^2),                                                                                                                                                                                      0, (a*b*rho*(10*L_PML_x^2 + 6*alpha_0_x*a^2 + 15*alpha_0_x*a*xi + 10*alpha_0_x*xi^2)*(10*L_PML_y^2 + 3*alpha_0_y*b^2 + 10*alpha_0_y*b*yj + 10*alpha_0_y*yj^2))/(1800*L_PML_x^2*L_PML_y^2),                                                                                                                                                                                      0,  (a*b*rho*(10*L_PML_x^2 + 6*alpha_0_x*a^2 + 15*alpha_0_x*a*xi + 10*alpha_0_x*xi^2)*(10*L_PML_y^2 + 6*alpha_0_y*b^2 + 15*alpha_0_y*b*yj + 10*alpha_0_y*yj^2))/(900*L_PML_x^2*L_PML_y^2),                                                                                                                                                                                      0,                                                                                                                                                                                   0,                                                                                                                                                                                   0,                                                                                                                                                                                   0;
                                                                                                                                                                                              0, (a*b*rho*(10*L_PML_x^2 + 3*alpha_0_x*a^2 + 10*alpha_0_x*a*xi + 10*alpha_0_x*xi^2)*(10*L_PML_y^2 + 6*alpha_0_y*b^2 + 15*alpha_0_y*b*yj + 10*alpha_0_y*yj^2))/(1800*L_PML_x^2*L_PML_y^2),                                                                                                                                                                                      0, (a*b*rho*(10*L_PML_x^2 + 3*alpha_0_x*a^2 + 10*alpha_0_x*a*xi + 10*alpha_0_x*xi^2)*(10*L_PML_y^2 + 3*alpha_0_y*b^2 + 10*alpha_0_y*b*yj + 10*alpha_0_y*yj^2))/(3600*L_PML_x^2*L_PML_y^2),                                                                                                                                                                                      0, (a*b*rho*(10*L_PML_x^2 + 6*alpha_0_x*a^2 + 15*alpha_0_x*a*xi + 10*alpha_0_x*xi^2)*(10*L_PML_y^2 + 3*alpha_0_y*b^2 + 10*alpha_0_y*b*yj + 10*alpha_0_y*yj^2))/(1800*L_PML_x^2*L_PML_y^2),                                                                                                                                                                                      0,  (a*b*rho*(10*L_PML_x^2 + 6*alpha_0_x*a^2 + 15*alpha_0_x*a*xi + 10*alpha_0_x*xi^2)*(10*L_PML_y^2 + 6*alpha_0_y*b^2 + 15*alpha_0_y*b*yj + 10*alpha_0_y*yj^2))/(900*L_PML_x^2*L_PML_y^2),                                                                                                                                                                                   0,                                                                                                                                                                                   0,                                                                                                                                                                                   0;
                                                                                                                                                                                              0,                                                                                                                                                                                      0,                                                                                                                                                                                      0,                                                                                                                                                                                      0,                                                                                                                                                                                      0,                                                                                                                                                                                      0,                                                                                                                                                                                      0,                                                                                                                                                                                      0,  (a*b*(nu^2 - 1)*(3*L_PML_x^2 + alpha_0_x*a^2 + 3*alpha_0_x*a*xi + 3*alpha_0_x*xi^2)*(3*L_PML_y^2 + alpha_0_y*b^2 + 3*alpha_0_y*b*yj + 3*alpha_0_y*yj^2))/(9*E*L_PML_x^2*L_PML_y^2), (a*b*nu*(nu + 1)*(3*L_PML_x^2 + alpha_0_x*a^2 + 3*alpha_0_x*a*xi + 3*alpha_0_x*xi^2)*(3*L_PML_y^2 + alpha_0_y*b^2 + 3*alpha_0_y*b*yj + 3*alpha_0_y*yj^2))/(9*E*L_PML_x^2*L_PML_y^2),                                                                                                                                                                                   0;
                                                                                                                                                                                              0,                                                                                                                                                                                      0,                                                                                                                                                                                      0,                                                                                                                                                                                      0,                                                                                                                                                                                      0,                                                                                                                                                                                      0,                                                                                                                                                                                      0,                                                                                                                                                                                      0, (a*b*nu*(nu + 1)*(3*L_PML_x^2 + alpha_0_x*a^2 + 3*alpha_0_x*a*xi + 3*alpha_0_x*xi^2)*(3*L_PML_y^2 + alpha_0_y*b^2 + 3*alpha_0_y*b*yj + 3*alpha_0_y*yj^2))/(9*E*L_PML_x^2*L_PML_y^2),  (a*b*(nu^2 - 1)*(3*L_PML_x^2 + alpha_0_x*a^2 + 3*alpha_0_x*a*xi + 3*alpha_0_x*xi^2)*(3*L_PML_y^2 + alpha_0_y*b^2 + 3*alpha_0_y*b*yj + 3*alpha_0_y*yj^2))/(9*E*L_PML_x^2*L_PML_y^2),                                                                                                                                                                                   0;
                                                                                                                                                                                              0,                                                                                                                                                                                      0,                                                                                                                                                                                      0,                                                                                                                                                                                      0,                                                                                                                                                                                      0,                                                                                                                                                                                      0,                                                                                                                                                                                      0,                                                                                                                                                                                      0,                                                                                                                                                                                   0,                                                                                                                                                                                   0, -(2*a*b*(nu + 1)*(3*L_PML_x^2 + alpha_0_x*a^2 + 3*alpha_0_x*a*xi + 3*alpha_0_x*xi^2)*(3*L_PML_y^2 + alpha_0_y*b^2 + 3*alpha_0_y*b*yj + 3*alpha_0_y*yj^2))/(9*E*L_PML_x^2*L_PML_y^2)];